networks:
  bgypsy-network:
    name: bgypsy

services:
  kafka:
    image: embedded-kafka-image:0.0.1-SNAPSHOT
    ports:
      - 9092:9092
      - 443:443
      - 8090:8090
      - 5005:5005
    volumes:
      - ./local/path:/container/path
    environment:
      io.github.dfauth.embedded.kafka.topics: test
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - bgypsy-network
    healthcheck:
      test: ["CMD", "../../bin-kafkatopics", "--list", "--bootstrap-server", "kafka:9092"]
      interval: 30s
      timeout: 10s
      retries: 5


